version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8082:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php
